version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: dev-stage
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development

  backend:
    build:
      context: ./backend
      target: ${NODE_ENV:-development}
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=mongo:27017
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASS=mypassword
      - JWT_SECRET=mysecret
    volumes:
      - ./src:/app/src:delegated
      - ./nodemon.json:/app/nodemon.json
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mydatabase
      - MONGO_INITDB_USER=myuser
      - MONGO_INITDB_PASSWORD=mypassword
    volumes:
      - mongo-data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  mongo-data:

  
