version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: test_db
    volumes:
      - mongo-test-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      target: test
    ports:
      - '5000:5000'
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://root:rootpassword@mongo:27017/test_db
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=test_secret
      - PORT=5000
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongo-test-data: