version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: dev-stage
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  socketio:
    build:
      context: ./backend
      dockerfile: Dockerfile.socketio
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV: development
      - FRONTEND_URL: http://localhost:5173
      - MONGODB_URI: mongodb://mongo:27017/yourdb

  backend:
    build:
      context: ./backend
      target: ${NODE_ENV:-development}
    container_name: backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    env_file:
      - ./backend/.env.development  # Path to the .env file
    volumes:
      - ./backend/src:/app/src:delegated
      - ./backend/nodemon.json:/app/nodemon.json
      - /app/node_modules
      - ./backend/uploads:/app/uploads  # profilepictures

volumes:
  mongo-data:
  uploads:

